### ISSUE TITLE
No such file or directory found

### ISSUE THREAD

**Issue by golokeshpatra45** [casualjim/yaml2json#2]
Please help me out

![image](https://user-images.githubusercontent.com/26374269/28054866-4b5a697c-6634-11e7-8a95-3552021c2766.png)

**Comment by casualjim** [comment]
what's the output of:

```
echo $GOPATH
echo $(which yaml2json)
[ -f /home/admin/StatusPage/Downloads/YAML/lkg-latest.yml ] && echo "file exists" || echo "file is not there"
```

**Comment by golokeshpatra45** [comment]
![image](https://user-images.githubusercontent.com/26374269/28060343-7c3a5376-6644-11e7-8a32-8d57ff54e69e.png)

I made a pip install and since then it works fine.
_pip install json2yaml_
